// credit https://www.texelate.co.uk/blog/uk-counties-in-php-and-json-format
export const COUNTIES = [
    'Aberdeenshire',
    'Angus',
    'Antrim',
    'Argyll',
    'Armagh',
    'Ayrshire',
    'Banffshire',
    'Berkshire',
    'Berwickshire',
    'Bristol',
    'Buckinghamshire',
    'Bute',
    'Caithness',
    'Cambridgeshire',
    'Cheshire',
    'City of London',
    'Clackmannanshire',
    'Clwyd',
    'Cornwall',
    'Cumbria',
    'Derbyshire',
    'Devon',
    'Dorset',
    'Down',
    'Dumfriesshire',
    'Dunbartonshire',
    'Durham',
    'Dyfed',
    'East Lothian',
    'East Riding of Yorkshire',
    'East Sussex',
    'Essex',
    'Fermanagh',
    'Fife',
    'Gloucestershire',
    'Greater London',
    'Greater Manchester',
    'Gwent',
    'Gwynedd',
    'Hampshire',
    'Herefordshire',
    'Hertfordshire',
    'Inverness-shire',
    'Isle of Wight',
    'Kent',
    'Kincardineshire',
    'Kinross-shire',
    'Kirkcudbrightshire',
    'Lanarkshire',
    'Lancashire',
    'Leicestershire',
    'Lincolnshire',
    'Londonderry',
    'Merseyside',
    'Mid Glamorgan',
    'Midlothian',
    'Moray',
    'Nairnshire',
    'Norfolk',
    'North Yorkshire',
    'Northamptonshire',
    'Northumberland',
    'Nottinghamshire',
    'Orkney',
    'Oxfordshire',
    'Peeblesshire',
    'Perthshire',
    'Powys',
    'Renfrewshire',
    'Ross and Cromarty',
    'Roxburghshire',
    'Rutland',
    'Selkirkshire',
    'Shetland',
    'Shropshire',
    'Somerset',
    'South Glamorgan',
    'South Yorkshire',
    'Staffordshire',
    'Stirlingshire',
    'Suffolk',
    'Surrey',
    'Sutherland',
    'Tyne and Wear',
    'Tyrone',
    'Warwickshire',
    'West Glamorgan',
    'West Lothian',
    'West Midlands',
    'West Sussex',
    'West Yorkshire',
    'Wigtownshire',
    'Wiltshire',
    'Worcestershire'
];